### ISSUE TITLE
CSS/styling for Simple WP membership pages

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-2016#288]
Some styling is required for the Login/registration pages created by the Simple WP membership login to better fit the new Wandelen voor Water site.

**Comment by samvthom16** [comment]
.swpm-login-widget-form{
  max-width: 350px;
  margin-left: auto;
  margin-right: auto;
  padding: 20px;
  border-radius: 5px;
  border: #CCC solid 1px;
}

To be added in the child theme
